apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: raspiled
  name: raspiled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raspiled
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: raspiled
    spec:
      containers:
      - image: samfrodo/raspiled:0.3
        name: raspiled
        env:
        - name: LED_DELAY
          value: "5.1"
        volumeMounts:
        - mountPath: /dev/gpiomem
          name: dev-gpiomem
        securityContext:
          privileged: true
      volumes:
      - name: dev-gpiomem
        hostPath:
          path: /dev/gpiomem
